-- Baseline generated by drizzle-kit from functions/_server/db/schema.ts.
-- Uses IF NOT EXISTS so it is a no-op on databases that were provisioned
-- by the legacy hand-written migrations (0001-0007, removed in this repo).
CREATE TABLE IF NOT EXISTS `images` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`source` text NOT NULL,
	`target` text NOT NULL,
	`profile` text DEFAULT 'default' NOT NULL,
	`enabled` integer DEFAULT 1 NOT NULL,
	`synced` integer DEFAULT 0 NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`synced_at` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`sync_error` text DEFAULT '' NOT NULL,
	`sync_run_id` text DEFAULT '' NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_images_user` ON `images` (`user_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `profiles` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`name` text NOT NULL,
	`registry` text DEFAULT '' NOT NULL,
	`username_env` text DEFAULT '' NOT NULL,
	`password_env` text DEFAULT '' NOT NULL,
	`credential_registry` text DEFAULT '',
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `profiles_user_id_name_unique` ON `profiles` (`user_id`,`name`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_profiles_user` ON `profiles` (`user_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `registry_secrets` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`registry` text NOT NULL,
	`dest_user` text NOT NULL,
	`dest_pass` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `registry_secrets_user_id_registry_unique` ON `registry_secrets` (`user_id`,`registry`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_registry_secrets_user` ON `registry_secrets` (`user_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` integer NOT NULL,
	`expires_at` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_sessions_user` ON `sessions` (`user_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_sessions_expires` ON `sessions` (`expires_at`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`email` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`github_id` integer,
	`name` text DEFAULT '' NOT NULL,
	`avatar_url` text DEFAULT '' NOT NULL,
	`is_admin` integer DEFAULT 0 NOT NULL,
	`password_hash` text,
	`status` text DEFAULT 'active' NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `users_email_unique` ON `users` (`email`);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `idx_users_github_id` ON `users` (`github_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_users_admin` ON `users` (`is_admin`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `idx_users_status` ON `users` (`status`);