ALTER TABLE images ADD COLUMN status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE images ADD COLUMN sync_error TEXT NOT NULL DEFAULT '';
ALTER TABLE images ADD COLUMN sync_run_id TEXT NOT NULL DEFAULT '';
