#:schema node_modules/wrangler/config-schema.json
name = "mirrorpilot-web"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding        = "DB"
database_name  = "mirrorpilot"
database_id    = "d9b21348-8005-4bd0-a429-ecd823bb981b"
migrations_dir = "migrations"
